name: stringprocess
description: A string library for common string operations and general text helper functions.
version: 1.0.5
author: Davy Mitchell <daftspaniel@gmail.com>
homepage: https://github.com/daftspaniel/stringprocess/
environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  html_unescape: ^0.1.5
  markdown: ^1.1.1

dev_dependencies:
  test: ^0.12.0
