name: stringprocess
description: A collection of string manipulation functions.
version: 0.0.1
#homepage: https://www.example.com
#author: daftspaniel <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  html_unescape: ^0.1.5
  markdown: ^0.11.1

dev_dependencies:
  test: ^0.12.0
